config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/destroy' => 'sessions#destroy'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')

  #delete '/subfeds/:id', to: 'subfeds#destroy', as: 'subfed'

  resources :users, only: [:index, :new, :create, :edit, :update] do
    patch 'users/:id', to: 'users#update'
    resources :comments, only: [:index]
  end

  resources :comments

  resources :subfeds, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  patch 'subfeds/:id', to: 'subfeds#update'

  resources :posts, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
  patch 'posts/:id', to: 'posts#update'
    resources :comments
end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :post
belongs_to :user

validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_logged_in, :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    if  params[:user_id]
      @user = User.find(params[:user_id])
      @comments = @user.comments
    else
      @comments = Comment.all
    end
    byebug
  end

  def new
    @comment = Comment.new
  end

 def create
   @comment = Comment.new(comment_params)
   @comment.post_id = params[:post_id]
   @comment.user_id = current_user.id
   if @comment.save
     redirect_to post_path(@comment.post)
   else
     render 'new'
   end
 end

 def update
   @comment = Comment.find(params[:id])
   @comment.update(comment_params)
   redirect_to post_path (@comment.post)
 end

 def destroy
   @comment = Comment.find(params[:id]).destroy
   redirect_to post_path(@comment.post)
 end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<section id="main">
  <div class="container">
    <h3>Post a Comment</h3>
      <%= form_for  ([@post, @comment]) do |f| %>

        <%= f.text_area :content %><br>

        <%= f.submit 'Submit' %>
      <% end %>
  </div>
</section>

app/views/comments/edit.html.erb
<h1> Edit comment </h1>

<%= form_for(@comment) do |f| %>

  <label>Content:</label><br>
  <%= f.text_area :content %><br>

  <%= f.submit "Update" %>
<% end %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
    <h2><%= comment.content %></h2>
  <% end %>

<%= link_to "Home", users_path %> <%= link_to "Create New Comment", new_post_comment_path %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<h1><%= @comment.content  %></h1>



<%= link_to "Back", comments_path %><br>
<%= link_to "Edit Comment", edit_comment_path(@comment) %><br>
<%= button_to "Delete Post", comment_path(@comment), method: :delete %><br>