config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/destroy' => 'sessions#destroy'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')

  #delete '/subfeds/:id', to: 'subfeds#destroy', as: 'subfed'

  resources :users, only: [:index, :new, :create, :edit, :update] do
    patch 'users/:id', to: 'users#update'
    resources :comments, only: [:index]
  end

  resources :comments

  resources :subfeds, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  patch 'subfeds/:id', to: 'subfeds#update'

  resources :posts, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
  patch 'posts/:id', to: 'posts#update'
    resources :comments
end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  require 'securerandom'

  has_secure_password
  has_many :settings
  has_many :subfeds
  accepts_nested_attributes_for :settings

  has_many :posts, foreign_key: :user_id, class_name: "Post", dependent: :destroy
  has_many :subfeds, through: :posts

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, length: { minimum: 5}

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @subfeds = Subfed.all
    @recent_subfeds = Subfed.all.recent(10)
    @recent_posts = Post.all.recent(10)
    @posts = Post.all
    @users = User.all
  end

  def new
    @user = User.new
    @user.settings.build(bio: "Tell us about you!")
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path(@user.id)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.settings == false
      @user.settings.build(bio: "Tell us about you!")
    end
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to users_path(@user)
    else
      render 'edit'
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :password, :email, :user_id, :settings_attributes => [:bio, :location, :age, :id, :_destroy ])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li class="font_color" ><%= message %></li>
			<% end %>
		</ul>
<% end %>

app/views/users/_form.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<body class="no-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1><%= @user.username %></h1>

            <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li><%= link_to "Back", users_path %></li>
                  <li class="current"><%= link_to @user.username, users_path %></li>
                </ul>
              </nav>
            </section>

            <!-- Main -->
              <section id="main">
                <div class="container">
                  <%= form_for @user do |f| %>
									<% if @user.errors.any? %>
												<% @user.errors.full_messages.each do |message| %>
													<p class="font_color" ><%= message %></p>
												<% end %>
									<% end %>
                    <%= f.label :email %>
                    <%= f.text_field :email %><br>

                    <%= f.label :password %>
                    <%= f.text_field :password %><br>

                  <h3>Settings</h3><br>
                  <%= f.fields_for :settings do |set| %>

                    <%= set.label :bio %>
                    <%= set.text_area :bio %><br>


                    <%= set.label :age %>
                    <%= set.text_field :age %><br>


                    <%= set.label :location %>
                   <%= set.text_field :location %><br>

                 <% end %>
                 <%= f.submit "Update!"%>
                 <% end %>
               </div>
             </section>

             <!-- Footer -->
               <section id="footer">
                 <div class="container">
                   <div class="row">
                     <div class="col-8 col-12-medium">
                     </div>
                     <div class="col-4 col-12-medium">
                     </div>
                     <div class="col-4 col-6-medium col-12-small">

                     </div>
                   </div>
                 </div>
               </section>

           </div>
         </body>
       </html>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
    <%= stylesheet_link_tag 'main' %>
		<title>Feddit</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="left-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1><%= link_to "Feddit", root_path %></h1>

					<!-- Nav -->
						<nav id="nav">
							<ul>
                <li><%= link_to "Subfeeds", subfeds_path %></li>
                <li><%= link_to "Posts", posts_path %></li>
								<li class="current"><%= link_to "Edit Settings", edit_user_path(@user)%></li>
                <li class="current"><%= link_to('Logout', {controller: 'sessions', action: 'destroy'},  method: 'post') %></li>
						<!--		<li><a href="right-sidebar.html">Right Sidebar</a></li> -->
						<!--	<li><a href="no-sidebar.html">No Sidebar</a></li> -->
							</ul>
						</nav>

				</section>

			<!-- Main -->
				<section id="main">
					<div class="container">
						<div class="row">
							<div class="col-4 col-12-medium">

								<!-- Login Sidebar -->
									<section class="box">
										<header>
											<h3><%= @user.username %></h3>
										</header>
											<ul class="divided">
												<% @user.settings.each do |user| %>
													<li>Bio: <%= user.bio%></li>
													<li>Age: <%= user.age%></li>
													<li>Location: <%= user.location %></li>
													<% end %>
												</ul>
										<footer>
										</footer>
									</section>
              <!-- Subfed Sidebar -->
									<section class="box">
										<header>
											<h3>Subfeeds</h3>
										</header>
										<p>Choose A Category</p>
										<ul class="divided">
                      <% @recent_subfeds.each do |subfeed| %>
                          <li><%= link_to subfeed.title, subfed_url(subfeed) %></li>
                      <% end %>
										</ul>
										<footer>
											<%= link_to "Create New Subfeed", new_subfed_path, class: "button alt" %></a>
										</footer>
									</section>

							</div>


								<!-- Content -->
								<div class="col-8 col-12-medium imp-medium">
								<% @recent_posts.each do |post| %>
								<Section id="main">
								<div class="container">
								<div class="col-8 col-12-medium imp-medium">
								    <article class="box post">
								  <header>
								    <h2><%= link_to post.title %></h2>
								      <p>Created By: <%= post.user.username %></p>
								  </header>
								  <ul class="actions">
								    <li><%= link_to "Continue Reading", post_url(post), class: "button icon solid fa-file-alt"  %></li>
								  </ul>
								</article>
								</div>
								<% end %>
							</section>

			<!-- Footer -->
				<section id="footer">
					<div class="container">
						<div class="row">
							<div class="col-8 col-12-medium">
								<section>


							</div>
						</div>
					</div>
				</section>

		</div>



	</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<body class="no-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1>Feddit</h1>

            <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li class = "current"><%= link_to "Home", root_path %></li>
                  <li><%= link_to "Login", login_path %></li>
                </ul>
              </nav>
            </section>

						<!-- errors -->


            <!-- Main -->
							<section id="main">
                <div class="container">
									<%= form_for @user, controller: 'users', action: 'create' do |f| %>
									<% if @user.errors.any? %>
												<% @user.errors.full_messages.each do |message| %>
													<p class="font_color" ><%= message %></p>
												<% end %>
									<% end %>
                  <%= f.label :username %>
                  <%= f.text_field :username %><br>

                  <%= f.label :email %>
                  <%= f.text_field :email %><br>

                  <%= f.label :password %>
                  <%= f.password_field :password %><br>
									<h3>Settings</h3><br>
									<%= f.fields_for :settings do |set| %>

										<%= set.label :bio %>
										<%= set.text_area :bio %><br>


										<%= set.label :age %>
										<%= set.text_field :age %><br>


										<%= set.label :location %>
									 <%= set.text_field :location %><br>

								 <% end %>

                  <%= f.submit "register" %>
                  <% end %>

							</div>
            </section>

              <!-- Footer -->
                <section id="footer">
                  <div class="container">
                    <div class="row">
                      <div class="col-8 col-12-medium">
                      </div>
                      <div class="col-4 col-12-medium">
                      </div>
                      <div class="col-4 col-6-medium col-12-small">

                      </div>
                    </div>
                  </div>
                </section>

              </div>
              </body>
              </html>