config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/destroy' => 'sessions#destroy'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')

  #delete '/subfeds/:id', to: 'subfeds#destroy', as: 'subfed'

  resources :users, only: [:index, :new, :create, :edit, :update] do
    patch 'users/:id', to: 'users#update'
    resources :comments, only: [:index]
  end

  resources :comments

  resources :subfeds, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  patch 'subfeds/:id', to: 'subfeds#update'

  resources :posts, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
  patch 'posts/:id', to: 'posts#update'
    resources :comments
end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/subfed.rb
class Subfed < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :content, presence: true

  belongs_to :user
  has_many :posts, foreign_key: :subfed_id, class_name: "Post", dependent: :destroy
  has_many :users, through: :posts

  scope :recent, -> (limit) { order("created_at desc").limit(limit) }

end

app/controllers/subfeds_controller.rb
class SubfedsController < ApplicationController
    before_action :require_logged_in
    before_action :current_user

  def index
    @subfeds = Subfed.all
    @recent_subfeds = Subfed.all.recent(10)
  end

  def new
    @subfed = current_user.subfeds.new
  end

  def edit
    @subfed = Subfed.find_by(id: params[:id])
  end

  def show
    @subfed =  Subfed.find_by(id: params[:id])
  end

  def create
    @subfed = Subfed.new(subfed_params)
    @subfed.user_id = current_user.id
    if @subfed.save
      flash[:success] = "You have succesfully created a new subfeed"
      redirect_to subfed_url(@subfed)
    else
      render 'new'
    end
  end

  def update
    @subfed = Subfed.find(params[:id])
    if @subfed.user_id == current_user.id
      @subfed.update(subfed_params)
      flash[:success] = "You have succesfully updated your Subfeed"
      redirect_to subfed_url(@subfed)
    else
      redirect_to users_path
    end
  end

  def destroy
    @subfed = Subfed.find(params[:id])
    if @subfed.user_id == current_user.id
      Subfed.find(params[:id]).destroy
      flash[:success] = "You have succesfully deleted your Subfeed"
      redirect_to subfeds_path
    else
      redirect_to users_path
    end
  end

  private

    def subfed_params
      params.require(:subfed).permit(:title, :content, :user_id)
    end

end

app/helpers/subfeds_helper.rb
module SubfedsHelper
end

app/views/subfeds/edit.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<body class="no-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1><%= @subfed.title %></h1>

            <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li><%= link_to "Back", subfed_path(@subfed) %></li>
                  <li class="current"><%= link_to @user.username, users_path %></li>
                </ul>
              </nav>
            </section>

            <!-- Main -->
      				<section id="main">
      					<div class="container">
                  <%= form_for(@subfed) do |f| %>

                  <label>Subfeed Title:</label><br>
                  <%= f.text_field :title %><br>

                  <label>Subfeed Description:</label><br>
                  <%= f.text_area :content %><br>

                  <%= f.submit "Update" %>
                  <% end %>
                </div>
              </section>

              <!-- Footer -->
                <section id="footer">
                  <div class="container">
                    <div class="row">
                      <div class="col-8 col-12-medium">
                      </div>
                      <div class="col-4 col-12-medium">
                      </div>
                      <div class="col-4 col-6-medium col-12-small">

                      </div>
                    </div>
                  </div>
                </section>

            </div>
          </body>
        </html>

app/views/subfeds/index.html.erb
<!-- <h1> Your Created Subfeeds! </h1>

<% @subfeds.each do |subfeed| %>
    <h2><%= link_to subfeed.title, subfed_url(subfeed) %></h2>
  <% end %>

<%= link_to "Home", users_path %>
<%= link_to "Create New Subfeed", new_subfed_path %> -->
<!DOCTYPE HTML>
<html>
<body class="no-sidebar is-preload">
  <div id="page-wrapper">

    <!-- Header -->
      <section id="header">

        <!-- Logo -->
          <h1>Feddit</h1>

          <!-- Nav -->
            <nav id="nav">
              <ul>
                <li class="current"><%= link_to @user.username, users_path %></li>
                <li><%= link_to "Create New Subfeed", new_subfed_path %></li>
              </ul>
            </nav>
          </section>

<% @recent_subfeds.each do |subfeed| %>
<Section id="main">
<div class="container">
<div class="col-8 col-12-medium imp-medium">
    <article class="box post">
  <header>
    <h2><%= subfeed.title %></h2>
  </header>
  <ul class="actions">
    <li><%= link_to "Enter", subfed_url(subfeed), class: "button icon solid fa-file-alt"  %></li>
  </ul>
</article>
</div>
<% end %>
<br>


</html>

app/views/subfeds/new.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<body class="no-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1>Feddit</h1>

            <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li><%= link_to "Back", subfeds_path %></li>
                  <li class="current"><%= link_to @user.username, users_path %></li>
                </ul>
              </nav>
            </section>

						<!-- errors -->

            <!-- Main -->
              <section id="main">
                <div class="container">
                  <%= form_for @subfed do |f| %>
									<% if @subfed.errors.any? %>
										<% @subfed.errors.full_messages.each do |message| %>
											<p class="font_color" ><%= message %></p>
										<% end %>
									<% end %>

                  <%= f.label "Title: " %><br>
                  <%= f.text_field :title %><br>

                  <%= f.label "Description: " %><br>
                  <%= f.text_area :content %><br>

                  <%= f.submit "Create Subforum" %>
                  <% end %>
                </div>
              </section>

              <!-- Footer -->
                <section id="footer">
                  <div class="container">
                    <div class="row">
                      <div class="col-8 col-12-medium">
                      </div>
                      <div class="col-4 col-12-medium">
                      </div>
                      <div class="col-4 col-6-medium col-12-small">

                      </div>
                    </div>
                  </div>
                </section>

            </div>
          </body>
        </html>

app/views/subfeds/show.html.erb
<!DOCTYPE HTML>
    <html>
      <body class="no-sidebar is-preload">
        <div id="page-wrapper">

          <!-- Header -->
    				<section id="header">

              <!-- Logo -->
    						<h1><%= @subfed.title %></h1><br>
                <p><%= @subfed.content %></p>

                <!-- Nav -->
                  <nav id="nav">
                    <ul>
                      <li class="current"><%= link_to @user.username, users_path %></li>
                      <li><%= link_to "Create New Post", new_post_path %></li>
                      <% if @subfed.user == @user %>
                      <li><%= link_to "Edit Subfeed", edit_subfed_path(@subfed)  %></li>
                      <li><%= button_to "Delete Subfeed", subfed_path(@subfed), method: :delete  %></li>
                      <% end %>
                    </ul>
                  </nav>
                </section>

          <% @subfed.posts.collect do |post| %>
          <Section id="main">
            <div class="container">
              <div class="col-8 col-12-medium imp-medium">
                <article class="box post">
                  <header>
                    <h2><%= link_to post.title, post_path(post.id) %></h2>
                  </header>
                  <ul class="actions">
                    <li><%= link_to "Continue Reading", post_url(post), class: "button icon solid fa-file-alt"  %></li>
                  </ul>
                </article>
              </div>
              <% end %>

  <!-- Footer -->
    <section id="footer">
      <div class="container">
        <div class="row">
          <div class="col-8 col-12-medium">
          </div>
          <div class="col-4 col-12-medium">
          </div>
          <div class="col-4 col-6-medium col-12-small">

          </div>
        </div>
      </div>
    </section>

</div>

</body>
  </html>