config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/destroy' => 'sessions#destroy'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')

  #delete '/subfeds/:id', to: 'subfeds#destroy', as: 'subfed'

  resources :users, only: [:index, :new, :create, :edit, :update] do
    patch 'users/:id', to: 'users#update'
    resources :comments, only: [:index]
  end

  resources :comments

  resources :subfeds, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  patch 'subfeds/:id', to: 'subfeds#update'

  resources :posts, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
  patch 'posts/:id', to: 'posts#update'
    resources :comments
end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :subfed
  belongs_to :user

  has_many :comments

  validates :title, presence: true
  validates :summary, presence: true

  scope :recent, -> (limit) { order("created_at desc").limit(limit) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_logged_in

  def index
    @posts = Post.all
    @recent_posts = Post.recent(10)
  end

  def new
    @post = current_user.posts.new
    @subfeds = Subfed.all
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def show
    @subfed = Subfed.find_by(params[:subfed_id])
    @post =  Post.find_by(id: params[:id])
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    @comment.user_id = session[:user_id]
    @comment.save
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "You have succesfully created a new Post"
      redirect_to post_path(@post.id)
    else
      @subfeds = Subfed.all
      render 'new'
    end
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.user_id == current_user.id
      @post.update(post_params)
      flash[:success] = "You have succesfully updated your Post"
      redirect_to post_url(@post)
    else
      redirect_to users_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post = Post.find(params[:id]).destroy
      flash[:success] = "You have succesfully deleted your Post"
      redirect_to posts_path
    else
      redirect_to users_path
    end
  end

  private

    def post_params
      params.require(:post).permit( :title, :summary, :subfed_id, :user_id)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="container">
      <article class="box post">
        <header>
          <p>Created By: <%= comment.user.username %></p>
          <h2><%= comment.content %></h2><br>
        </header>
      </article>
    </div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<%= f.label "Title: " %><br>
<%= f.text_field :title %><br>

<%= f.label "Summary: " %><br>
<%= f.text_area :summary %><br>

<%= f.label :subfed_id, "Subfeed" %><br>
<%= f.collection_select :subfed_id, @subfeds, :id, :title, { prompt: true } %><br>

<%= f.submit "Create Post" %>
<% end %>

app/views/posts/edit.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<body class="no-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1><%= @post.title %></h1>

            <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li><%= link_to "Back", posts_path(@post) %></li>
                  <li class="current"><%= link_to @user.username, users_path %></li>
                </ul>
              </nav>
            </section>

            <!-- Main -->
      				<section id="main">
      					<div class="container">
                  <%= form_for(@post) do |f| %>

                  <label>Post Title:</label><br>
                  <%= f.text_field :title %><br>

                  <label>Summary:</label><br>
                  <%= f.text_area :summary %><br>

                  <%= f.submit "Update" %>
                  <% end %>
                </div>
              </section>

              <!-- Footer -->
                <section id="footer">
                  <div class="container">
                    <div class="row">
                      <div class="col-8 col-12-medium">
                      </div>
                      <div class="col-4 col-12-medium">
                      </div>
                      <div class="col-4 col-6-medium col-12-small">

                      </div>
                    </div>
                  </div>
                </section>

            </div>
          </body>
        </html>

app/views/posts/index.html.erb
<!DOCTYPE HTML>
<html>
<body class="no-sidebar is-preload">
  <div id="page-wrapper">

    <!-- Header -->
      <section id="header">

        <!-- Logo -->
          <h1>Feddit</h1>

          <!-- Nav -->
            <nav id="nav">
              <ul>
                <li class="current"><%= link_to @user.username, users_path %></li>
                <li><%= link_to "Create New Post", new_post_path %></li>
              </ul>
            </nav>
          </section>

<% @recent_posts.each do |post| %>
<Section id="main">
<div class="container">
<div class="col-8 col-12-medium imp-medium">
    <article class="box post">
  <header>
    <h2><%= link_to post.title %></h2>
      <p>This will be a subfed title belonging to post</p>
  </header>
  <ul class="actions">
    <li><%= link_to "Continue Reading", post_url(post), class: "button icon solid fa-file-alt"  %></li>
  </ul>
</article>
</div>
<% end %>
<br>


</html>

app/views/posts/new.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<body class="no-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1>Feddit</h1>

            <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li><%= link_to "Back", subfeds_path %></li>
                  <li class="current"><%= link_to @user.username, users_path %></li>
                </ul>
              </nav>
            </section>

            <!-- Main -->
              <section id="main">
                <div class="container">
                  <%= form_for @post do |f| %>
									<% if @post.errors.any? %>
										<% @post.errors.full_messages.each do |message| %>
											<p class="font_color" ><%= message %></p>
										<% end %>
									<% end %>

                  <%= f.label "Title: " %><br>
                  <%= f.text_field :title %><br>

                  <%= f.label "Summary: " %><br>
                  <%= f.text_area :summary %><br>

                  <%= f.label :subfed_id, "Subfeed" %><br>
									<% unless @subfeds.nil? %>
                  <%= f.collection_select :subfed_id, @subfeds, :id, :title, { prompt: true, required: true } %><br>
									<% end %>

                  <%= f.submit "Create Post" %>
                  <% end %>
                </div>
              </section>

              <!-- Footer -->
                <section id="footer">
                  <div class="container">
                    <div class="row">
                      <div class="col-8 col-12-medium">
                      </div>
                      <div class="col-4 col-12-medium">
                      </div>
                      <div class="col-4 col-6-medium col-12-small">

                      </div>
                    </div>
                  </div>
                </section>

            </div>
          </body>
        </html>

app/views/posts/show.html.erb
<!DOCTYPE HTML>
<!--
	Dopetrope by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<body class="no-sidebar is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">

					<!-- Logo -->
						<h1><%= link_to @post.subfed.title, subfed_path(@post.subfed) %></h1>

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><%= link_to "Back", subfed_path(@post.subfed) %></li>
                <li class="current"><%= link_to @user.username, users_path %></li>
							</ul>
						</nav>
          </section>

			<!-- Main -->
				<section id="main">
					<div class="container">

						<!-- Content -->
							<article class="box post">
								<header>
									<h2><%=@post.title %></h2>
									<p>Created By: <%= @post.user.username %> </p>
								</header>
								<p>
								  <%= @post.summary %>
								</p>
								<section>
									<% if @post.user == @user %>
                  <ul class="actions">
                    <li><%= link_to "Edit Post", edit_post_path(@post), class: "button icon solid fa-file-alt" %></li>
                    <li><%= button_to "Delete Post", post_path(@post), class: "button icon solid fa-file-alt", method: :delete %></li>
                  </ul>
									<% end %>
								</section>
							</article>
              <%= render partial: 'comments/form' %>
					</div>
					<% @post.comments.each do |comment| %>
					<div class="container">
								<article class="box post">
									<header>
										<h3 class="comment">Created By: <%= comment.user.username %></h3>
									</header>
									<p class="comment"><%= comment.content %></p><br>
								</article>
							</div><br>
						<% end %>
				</section>

			<!-- Footer -->
				<section id="footer">
					<div class="container">
						<div class="row">

							<div class="col-8 col-12-medium">
							</div>
							<div class="col-4 col-12-medium">
							</div>
							<div class="col-4 col-6-medium col-12-small">

							</div>
						</div>
					</div>
				</section>

		</div>

	</body>
</html>